import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import PrelineWrapper from "./components/PrelineWrapper";
import Nav from "./components/nav";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  //   useEffect(() => {
  //   // Preline runs in browser only
  //   import("preline/preline");
  // }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <PrelineWrapper><Providers>
          <Nav></Nav>
          {children}
          <Footer></Footer>
          </Providers></PrelineWrapper>
      </body>
    </html>
  );
}
